project_name: chewa

dist: .builds

before:
  hooks:
    - go mod tidy

builds:
  - env: [CGO_ENABLED=0]
    main: ./src
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
